### ISSUE TITLE
False error: "It doesn't look like your Photon has made it to the cloud yet."

### ISSUE THREAD

**Issue by pomplesiegel** [spark/particle-cli#127]
After setting up 5 photons in a row, the fifth is happily connected to our network, breathing cyan. However, cli repeatedly reads 

````sh
! It doesn't look like your Photon has made it to the cloud yet.

? What would you like to do? (Use arrow keys)
❯ Reconfigure the Wi-Fi settings of the Photon 
  Check again to see if the Photon has connected 
````

When pressing `Check again`... it comes right back to this screen, even though the Photon is connected. Had to begin setup again to name this Photon and finish setup.

**Comment by pomplesiegel** [comment]
Occurred again just now on another photon. Fairly annoying, as now this one must be fished out of the pile and renamed. 
![image](https://cloud.githubusercontent.com/assets/1450352/9887262/b141f59a-5bbc-11e5-8ca9-070ab497ab85.png)

**Comment by brycekahle** [comment]
Do you have a device id we can check? (PM on Slack is fine). I wonder if something failed during claiming.

**Comment by emilyrose** [comment]
sounds like we need another option to just say "Nevermind, it made it!"

It's interesting though, because the check that happens here is seeing if the device actually made a cloud connection.

**Comment by pomplesiegel** [comment]
Interesting!
This may actually be due to a larger issue we've seen repeatedly before: 
A device is very much online (breathing cyan and responds to `get`s) but `particle list`, an API call and the dashboard all show it is offline. It is for this reason that we no longer use the Particle cloud to indicate if a customer's product is actually online.

**Comment by brycekahle** [comment]
We've fixed some online/offline reporting issues in the API, which was the root cause of this issue.

**Comment by boristomas** [comment]
This issue is still present :(

**Comment by claus3witz** [comment]
I'm also still experiencing this issue, unfortunately. Any updates?
